### ISSUE TITLE
サークルメンバーがメンバー同士の活動を把握でき、入会希望者がどんな人がいるかを把握できる。

### ISSUE THREAD

**Issue by Yoshiki-Yamada** [CIST-LT-CLUB/cistLT_HomePage#1]
MemberCardをクリックしたらメンバープロフィールページに遷移する。
メンバープロフィールページでSNSリンク、個人サイトのリンクの掲載をする。

## 詳細なタスク  
0pt 1pt(30min)

- [x] メンバープロフィールページを作る  1pt

- [x] MemberCardの画像にリンク Linkで囲む 1pt 

- [ ] メンバープロフィールページに個人のSNSリンク、個人サイトのリンクをContentfulで管理して掲載する 1pt

- [x] Twitter Github Facebook instagram Portofolio のリンクかき集める 0pt

- [ ] リンクがない場合の処理を実装する 1pt

- [x] Twitter Github Facebook instagram Portofolio のリンクをContentfulで管理しておく 0pt

- [ ] メンバープロフィールページをレスポンシブ対応  1pt

## 参考画像
![aaa](https://user-images.githubusercontent.com/44164993/101353564-241df800-38d7-11eb-8e96-723b596db261.png)

**Comment by k-oketa** [comment]
# 😆
応援してます！頑張ってください！

**Comment by OHMORIYUSUKE** [comment]
終了しました。
